//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/MyFiles/Projects/WS/runtime-EclipseApplication/BuinessLogicTest/src/com/laex/businesslogic/Income.java
//
//  Created by hemantasapkota on 3/30/13.
//

#line 1 "/Volumes/MyFiles/Projects/WS/runtime-EclipseApplication/BuinessLogicTest/src/com/laex/businesslogic/Income.java"

#import "Income.h"
#import "java/lang/StringBuilder.h"

#line 4
@implementation Income

@synthesize income = income_;
@synthesize hours = hours_;
@synthesize rate = rate_;

#line 9
- (id)initWithInt:(int)hours
          withInt:(int)rate {
  if ((self = [super init])) {
    self.hours = hours;
    self.rate = rate;
  }
  return self;
}

#line 14
- (void)calculate {
#line 15
  self.income = hours_ * rate_;
}

#line 18
- (int)getIncome {
#line 19
  return income_;
}

- (NSString *)description {
#line 24
  return [[[((JavaLangStringBuilder *) [[JavaLangStringBuilder alloc] init]) appendWithNSString:@"Income Tax: "] appendWithInt:self.income] description];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  Income *typedCopy = (Income *) copy;
  typedCopy.income = income_;
  typedCopy.hours = hours_;
  typedCopy.rate = rate_;
}

@end
