//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/MyFiles/Projects/WS/runtime-EclipseApplication/BuinessLogicTest/src/com/laex/businesslogic/Income.java
//
//  Created by hemantasapkota on 3/30/13.
//

#import "JreEmulation.h"

@interface Income : NSObject {
 @public
  int income_;
  int hours_;
  int rate_;
}

@property (nonatomic, assign) int income;
@property (nonatomic, assign) int hours;
@property (nonatomic, assign) int rate;

- (id)initWithInt:(int)hours
          withInt:(int)rate;
- (void)calculate;
- (int)getIncome;
- (NSString *)description;
@end

typedef Income ComLaexBusinesslogicIncome;
